Use #[cfg] attribute rather than cfg! macro
Though the boolean evaluation of the cfg! macro is done in compilation
time, the scoped block is compile regardless that evaluation. Thus,
when compiling in linux this compilation error shows up:

../channel_player.rs:197: undefined reference to `gdk_quartz_window_get_nsview'
collect2: error: ld returned 1 exit status

This patch changes the cfg! macro to compiler's #[cfg] attribute.